### ISSUE TITLE
clipboard input Chinese support?

### ISSUE THREAD

**Issue by aniude** [ich777/docker-chrome#1]
![Screenshot 2022-12-31 002118](https://user-images.githubusercontent.com/1137266/210091293-9992ff7b-5935-4379-97e2-220e623afe51.jpg)
![Screenshot 2022-12-31 002332](https://user-images.githubusercontent.com/1137266/210091555-806cc9d6-b0e6-46ab-9a7f-e0f9bb82081e.jpg)

It seem that the Chinese Input copy paste into browser can't be display normal? How to fix it?

**Comment by ich777** [comment]
There is no fix currently and nothing I can do about since TurboVNC doesn't support Unicode just yet.
When TurboVNC 3.1 is released everything should work but that will take some additional time, see also this open issue here for my noVNC base image: https://github.com/ich777/docker-novnc-baseimage/issues/1

Please feel free to let the issue open until it's solved but I would rather close it and track in the noVNC base image repository.

**Comment by aniude** [comment]
thanks for reply.  I will wait for the issue be fixed.

using the web browser input method for unicode character is my temp resolve solution.

**Comment by Magician-MO** [comment]
Hi, I see TurboVNC 3.1 is is released, would you mind switching the TurboVNC version in the image? For the UTF-8 clipboard problem.

**Comment by Magician-MO** [comment]
> There is no fix currently and nothing I can do about since TurboVNC doesn't support Unicode just yet. When TurboVNC 3.1 is released everything should work but that will take some additional time, see also this open issue here for my noVNC base image: [ich777/docker-novnc-baseimage#1](https://github.com/ich777/docker-novnc-baseimage/issues/1)
> 
> Please feel free to let the issue open until it's solved but I would rather close it and track in the noVNC base image repository.

Hi, I see TurboVNC 3.1 is is released, would you mind switching the TurboVNC version in the image? For the UTF-8 clipboard problem.

**Comment by ich777** [comment]
> Hi, I see TurboVNC 3.1 is is released, would you mind switching the TurboVNC version in the image? For the UTF-8 clipboard problem.

Thanks for heads up, please give me one or two days and I will update the container.

**Comment by ich777** [comment]
@aniude & @Magician-MO I have now updated the container so that it now includes TurboVNC 3.1

**Comment by ich777** [comment]
I‘ll close this issue for now, if you have any further wuestions feel free to reopen this issue or create a new issue.
