### ISSUE TITLE
Can we log in the google account and sync the data?

### ISSUE THREAD

**Issue by chca2** [ich777/docker-chrome#2]
Can we log in the google account and sync the data? Seems not working every time I tried.

**Comment by ich777** [comment]
Can you please describe a bit more in depth what do you mean that it doesn't work every time?
Does it work or not? Do you have to login every time you restart the container?

**Comment by chca2** [comment]
> Can you please describe a bit more in depth what do you mean that it doesn't work every time? Does it work or not? Do you have to login every time you restart the container?

Every time I tried to log in the built-in sync function in Chrome and it popped up the log in page correctly. But once I  typed the email and password. Nothing changed and the avatar icon is still the default one and the user is also the original.

**Comment by ich777** [comment]
After a little research I now got it. Since this container is based on Chromium it's not possible to log in anymore (IIRC this was done intentionally by Google and there is nothing I can do about that).

**Comment by chca2** [comment]
> After a little research I now got it. Since this container is based on Chromium it's not possible to log in anymore (IIRC this was done intentionally by Google and there is nothing I can do about that).

Okay. I also searched and seems   Google has banned it. Thank you as well.
